### ISSUE TITLE
Sonic Pi, jungle doctor who, "pl" function 

### ISSUE THREAD

**Issue by MAKIO135** [YorkDojo/yorkdojo.github.io#2]
https://github.com/YorkDojo/yorkdojo.github.io/blob/8a5a10859bd6947d077cbd802d808e9e1e487f5c/_worksheets/sonic-pi/doctor-who/jungle-doctor-who.rb#L48

Is `pl` a replacement for `play_pattern_timed`?

**Comment by acallaghan** [comment]
Yes it is - sorry, I’ll fix that now

Thanks for the heads up!

**Comment by acallaghan** [comment]
Fixed
